# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.EmailField(default='', max_length=254, verbose_name='Recipient'),
            preserve_default=False,
        ),
    ]
