# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0003_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(default=b'2017-02-27 03:23:58.066631+00:00', help_text='Designated handle', max_length=120, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
