# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0004_emailtemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_model', models.CharField(max_length=500)),
                ('trigger_query_str', models.CharField(max_length=500)),
                ('trigger_condition', models.CharField(max_length=500)),
                ('context_method_name', models.CharField(max_length=500)),
                ('delay', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_message',
            field=models.TextField(default='', help_text="Hint: You can use Django's template tags", verbose_name='HTML Message'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='message',
            field=models.TextField(default='', help_text="Hint: You can use Django's template tags", verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='', help_text="Hint: You can use Django's template tags", max_length=989, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='ruletemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iyimail.EmailTemplate'),
        ),
    ]
