# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0005_auto_20170227_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruletemplate',
            name='delay',
        ),
        migrations.AlterField(
            model_name='ruletemplate',
            name='trigger_condition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ruletemplate',
            name='trigger_query_str',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
