# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0006_auto_20170227_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruletemplate',
            name='trigger_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='For time based triggers. timedelta(days=N)'),
        ),
        migrations.AlterField(
            model_name='ruletemplate',
            name='trigger_condition',
            field=models.CharField(blank=True, help_text='Overrides trigger_age', max_length=500, null=True),
        ),
    ]
