# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0009_auto_20170228_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 2, 22, 46, 31, 360291, tzinfo=utc), verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
