# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0010_executionlog_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='activate_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 23, 1, 33, 90613, tzinfo=utc), verbose_name='Activate At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='disable_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disable At'),
        ),
    ]
