# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0011_auto_20170303_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='activate_at',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='disable_at',
        ),
    ]
