# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iyimail', '0012_auto_20170303_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruletemplate',
            name='activate_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 23, 26, 19, 362215, tzinfo=utc), verbose_name='Activate At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruletemplate',
            name='disable_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disable At'),
        ),
    ]
